### ISSUE TITLE
Adopt eslint-config-standard-with-typescript

### ISSUE THREAD

**Issue by swansontec** [swansontec/eslint-config-standard-kit#1]
Switching from `@typescript-eslint/eslint-plugin` recommended rules (with customizations) to [`eslint-config-standard-with-typescript`](https://github.com/standard/eslint-config-standard-with-typescript) will add many new rules. Work with upstream to figure out some kind of consensus, particularly around the new rules without auto-fixes:

* Extra verbosity:
  * [x] `@typescript-eslint/explicit-function-return-type` [issue](https://github.com/standard/eslint-config-standard-with-typescript/issues/110)
  * [x] `@typescript-eslint/explicit-member-accessibility` [issue](https://github.com/standard/eslint-config-standard-with-typescript/issues/111)
* Bad practices:
  * [ ] `@typescript-eslint/no-extraneous-class`
  * [ ] `@typescript-eslint/no-this-alias`
  * [ ] `@typescript-eslint/no-triple-slash-reference` (rule doesn't exist?)
  * [x] `@typescript-eslint/no-unused-vars` (removed args) [pr](https://github.com/standard/eslint-config-standard-with-typescript/pull/112)
  * [ ] `@typescript-eslint/no-useless-constructor`
  * [ ] `@typescript-eslint/promise-function-async`
* Potential bugs:
  * [ ] `@typescript-eslint/no-for-in-array`
  * [ ] `@typescript-eslint/require-array-sort-compare`
  * [ ] `@typescript-eslint/restrict-plus-operands`

## All changes

For reference, here is a comprehensive list of all the changes switching to `eslint-config-standard-with-typescript` would produce:

Structure:
* Everything moves inside an `overrides` section.
* `parserOptions` goes away.

Removed rules:
* `@typescript-eslint/ban-types`
* `@typescript-eslint/class-name-casing`
* `@typescript-eslint/interface-name-prefix`
* `@typescript-eslint/no-explicit-any` (warn)
* `@typescript-eslint/no-parameter-properties`
* `@typescript-eslint/no-triple-slash-reference`
* `@typescript-eslint/prefer-namespace-keyword`
* `no-use-before-define` (off) [pr](https://github.com/standard/eslint-config-standard-with-typescript/pull/113)

Changed rules:
* `@typescript-eslint/no-unused-vars` (removed args)
* `@typescript-eslint/indent` (many changes, 🔧)
* `@typescript-eslint/no-use-before-define` (added typedefs)

New rules:
* `@typescript-eslint/array-type` (🔧)
* `@typescript-eslint/camelcase`(in Standard.js)
* `@typescript-eslint/explicit-function-return-type`
* `@typescript-eslint/explicit-member-accessibility`
* `@typescript-eslint/no-extraneous-class`
* `@typescript-eslint/no-for-in-array`
* `@typescript-eslint/no-this-alias`
* `@typescript-eslint/no-triple-slash-reference`
* `@typescript-eslint/no-unnecessary-type-assertion` (🔧)
* `@typescript-eslint/no-useless-constructor`
* `@typescript-eslint/prefer-function-type` (🔧)
* `@typescript-eslint/promise-function-async`
* `@typescript-eslint/require-array-sort-compare`
* `@typescript-eslint/restrict-plus-operands`
* `no-undef`: (off)
* `no-useless-constructor`: (off)

**Comment by mightyiam** [comment]
I didn't pay attention to autofix while curating the rules for esling-config-standard-with-typescript. Yet I do enjoy autofix when it's available.

**Comment by swansontec** [comment]
@mightyiam Thanks for taking a look at this, and sorry for the sudden flood of issues and PR's on your repo!

My current thinking is that the new rules in the "bad practices" and "potential bugs" categories look useful, even without auto-fixes, so adopting them will be a useful (but breaking) change for `eslint-config-standard-kit`.

I am willing to accept style rules like `array-type` that have automatic fixes, even if I disagree with them personally. On the other hand, since these rules *are* highly opinionated, we need to document them in the same spirit as the [standardjs.com rules page](https://standardjs.com/rules.html). That way, people know what they are choosing when they adopt this particular style.

**Comment by mightyiam** [comment]
No worries. I'll take give the PRs proper attention.

Let's do this.

**Comment by mightyiam** [comment]
:smile:
